/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Actions: typeof import('./src/components/Actions.vue')['default']
    ColorModeButton: typeof import('./src/components/ColorModeButton.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    GrowingBed: typeof import('./src/components/GrowingBed.vue')['default']
    GrowingBeds: typeof import('./src/components/GrowingBeds.vue')['default']
    PlantIcon: typeof import('./src/components/PlantIcon.vue')['default']
    Plants: typeof import('./src/components/Plants.vue')['default']
    RightPanel: typeof import('./src/components/RightPanel.vue')['default']
    Selected: typeof import('./src/components/Selected.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
