/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorModeButton: typeof import('./src/components/ColorModeButton.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    PlantIcon: typeof import('./src/components/PlantIcon.vue')['default']
    Plants: typeof import('./src/components/Plants.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
